id: IB7700717
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T19:49:54+00:00'
last_modified: '2022-06-09T05:15:08.792786+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC17
  title: དགའ་ལྡན་ཁྲི་ཆེན་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AFE7:
      image_group_id: I2PD18536
      title: ''
      total_pages: 428
      order: 1
      base_file: AFE7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
