id: P008208
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:08:06.195078
source_metadata:
  id: bdr:W1AC17
  title: དགའ་ལྡན་ཁྲི་ཆེན་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    58675c05cea1469da1effdf98d7ce34a:
      image_group_id: I2PD18536
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
