id: P008208
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC17
  title: དགའ་ལྡན་ཁྲི་ཆེན་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    58675c05cea1469da1effdf98d7ce34a:
      image_group_id: I2PD18536
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
